name: Build and push Docker image to DockerHub
on: push
jobs:
  push_to_repository:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: checkout my rep code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hkseal/docker-git-integrated:mynewimage

